BE_001.Web/Areas/Cart/Pages/Cart/CheckOut.cshtml.cs
using BE_001.Web.Models;
using BE_001.Web.Repositories.Items;
using BE_001.Web.Services.Browsing;
using BE_001.Web.Services.Cart;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BE_001.Web.Areas.Cart.Pages.Cart;

public class CheckOutModel : PageModel
{
    private readonly IBrowsingService _browsingService;
    private readonly ICartService _cartService;

    public CheckOutModel(IBrowsingService browsingService, ICartService cartService)
    {
        _browsingService = browsingService;
        _cartService = cartService;
    }

    [BindProperty] public IEnumerable<Item> Items { get; set; } = new List<Item>();

    [BindProperty] public int ItemId { get; set; }
    
    [BindProperty] public string ReturnUrl { get; set; }
    
    public void OnGet()
    {
        Items = _cartService.GetItems().ToList();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        _cartService.AddToCart(await _browsingService.GetItem(ItemId));
        return LocalRedirect(ReturnUrl ?? "~/");
    }

    public IActionResult OnPostCheckout()
    {
        // add order creation here
        
        _cartService.ClearCart();
        return LocalRedirect("~/Cart/Cart/Confirmation");
    }

    public async Task<IActionResult> OnPostRemove()
    {
        _cartService.RemoveFromCart(await _browsingService.GetItem(ItemId));
        Items = _cartService.GetItems().ToList();
        return Page();
    }
}

BE_001.Web/Areas/Cart/Pages/Cart/CheckOut.cshtml
@page
@model CheckOutModel

<h2 class="mb-3">Your cart:</h2>
@if (Model.Items.Any())
{
    <ul class="list-group">
        @foreach (var item in Model.Items)
        {
            <li class="list-group-item">
                <div class="container text-center">
                    <div class="row">
                        <div class="col">
                            <img src="@item.ImgUrl" alt="@item.Name" style="max-width: 100px"/>
                        </div>
                        <div class="col-6">
                            <h3 class="mb-1">@item.Name</h3>
                            <span class="p-1">@item.Description</span>
                            <span>@item.Price.ToString("C")</span>
                        </div>
                        <div class="col">
                            <form asp-page-handler="Remove" method="post">
                                <input type="hidden" name="@nameof(item.ItemId)" value="@item.ItemId"/>
                                <button class="btn btn-danger" type="submit">Remove</button>
                            </form>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
    
    <p class="h3">Total</p>
    <p>@Model.Items.Sum(x => x.Price).ToString("C")</p>
                                                   
    <form asp-page-handler="Checkout" method="post">
        <button class="btn btn-primary" type="submit">Checkout</button>
    </form>
}
else
{
    <p class="h3">Cart is empty</p>
}

BE_001.Web/Areas/Cart/Pages/Cart/Confirmation.cshtml
@page

<h2>Thanks for buying! You will be redurected to home page after 5seconds...</h2>

<script>
    setTimeout(() => location.href = "/", 5000);
</script>